# Generated by Django 3.0.6 on 2020-05-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[('processing', 'Processing'), ('correcting', 'Correcting'), ('error', 'Error'), ('resolved', 'resolved')], default='processing', max_length=32),
        ),
    ]
