# Generated by Django 3.0.6 on 2020-05-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error'), ('refunding', 'Refunding'), ('refunded', 'Refunded'), ('fixing', 'Fixing')], default='processing', max_length=32),
        ),
    ]
